version: 1.0.{build}
image: Visual Studio 2019
environment:
  WINDOWS_SIGNING_TOOLS_URL: 
    secure: BQZZ+U5LmX/t6DUF3AbPFxvmDYrKoLUI5aVvTMOho0FrkHrxR+vGKYEeCKxtWPMKjlA0q60lii+cP8VNbpMo3Q==
  WINDOWS_SIGN_AUTH: 
    secure: 7gsvPGqUrq3mr0wXpdWyq00GvJY7CDoS3vzMdkXN1dZGsoS2xihAD5zRJ+/lGqig
  WINDOWS_SIGN_USER: 
    secure: PC1hesS7kuWn96McAzOcCxkgVQkc9yaOdUm2IlNXico=
  WINDOWS_CERT_SHA1:
    secure: C3sIp2WeLpZko1ohGcKwO2rO2i8yh/9KkHcBHTGQiBGq+gjYfgM/d5KYDDsvSS4o
  WINDOWS_SIGN_TOOL: C:\Program Files (x86)\Windows Kits\10\bin\10.0.18362.0\x64\signtool.exe
  GH_TOKEN:
    secure: 3gKqe7aTP4hMA4T1CrLF2G+3zf01ciR5NNeIAMIealG4hkjnMdl44L0c6tAIvGHg
#init:
#  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
install:
- cmd: >-
    reg add "HKEY_LOCAL_MACHINE\Software\Microsoft\Command Processor" /v EnableExtensions /d 1 /t REG_DWORD /f

    choco install -y make unzip curl
    
    make travis-setup SHELL=cmd
build_script:
- cmd: make travis-release SHELL=cmd
