# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
builds:
  - env:
    - CGO_ENABLED=0
    goos:
    - linux
    - freebsd
    - openbsd
    goarch:
      - amd64
      - arm
      - arm64
    ldflags:
    - -s -w -X "github.com/kopia/kopia/repo.BuildVersion={{.Version}}" -X "github.com/kopia/kopia/repo.BuildInfo={{.Commit}}" -X "github.com/kopia/kopia/repo.BuildGitHubRepo={{.Env.GITHUB_REPOSITORY}}"
  - id: kopia_boring
    binary: kopia_boring
    env:
      - CGO_ENABLED=1
      - GOEXPERIMENT=boringcrypto
      - CC=gcc
      - CXX=g++
      - GO_EXTLINK_ENABLED=0
    ldflags:
      - -s -w -extldflags "-static" -X "github.com/kopia/kopia/repo.BuildVersion={{.Version}}" -X "github.com/kopia/kopia/repo.BuildInfo={{.Commit}}" -X "github.com/kopia/kopia/repo.BuildGitHubRepo={{.Env.GITHUB_REPOSITORY}}"
    goos: [linux]
    goarch: [amd64]
release:
  draft: false
archives:
  - id: default
    replacements:
      darwin: macOS
      linux: linux
      windows: windows
      freebsd: freebsd-experimental
      openbsd: openbsd-experimental
      amd64: x64
    name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ .Binary }}"
    wrap_in_directory: true
    format_overrides:
    - goos: windows
      format: zip
    files:
      - LICENSE
      - README.md
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: '{{ .Env.KOPIA_VERSION_NO_PREFIX }}'
nfpms:
  - homepage: https://kopia.io
    vendor: Kopia Project
    maintainer: Kopia Project <kopia-pmc@googlegroups.com>
    description: Fast and secure open source backup.
    license: Apache 2.0
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ .Binary }}"
    replacements:
      arm: armhf
    formats:
    - deb
    - rpm
    bindir: /usr/bin
    overrides:
      rpm:
        file_name_template: "{{ .ProjectName }}-{{ .Version }}.{{ .Arch }}{{ .Binary }}"
        replacements:
          amd64: x86_64
          arm64: aarch64
          arm: armhfp
signs:
  - id: all
    artifacts: checksum
    cmd: tools/sign.sh
    args: ["${artifact}", "${signature}"]
changelog:
  filters:
    exclude:
    - '^docs:'
    - '^test:'
