dist: bionic
osx_image: xcode11.2
language: go
go:
- 1.13.x
os:
- linux
- osx
- windows
addons:
  apt:
    packages:
    - rpm
  snaps:
    - name: snapcraft
      classic: true
before_install:
- |-
    case $TRAVIS_OS_NAME in
      windows)
        choco install --no-progress -y make unzip curl
        ;;
      osx):
        sudo xcode-select -r
        ;;
    esac
install: travis_retry make travis-setup
script: make travis-release
cache:
  directories:
  - $HOME/.cache/electron
  - $HOME/.cache/electron-builder
  - $HOME/.cache/electron-docker
  - $HOME/.cache/electron-builder-docker
deploy:
- provider: pages
  cleanup: false
  skip_cleanup: true
  token: "$GITHUB_TOKEN"
  keep_history: false
  local_dir: site/public
  repo: kopia/kopia.github.io
  target_branch: master
  on:
    repo: kopia/kopia
    branch: master
    condition: $TRAVIS_OS_NAME = linux
git:
  depth: 9999999
env:
- GO111MODULE=on
