dist: bionic
language: go
go:
- 1.16.x
os:
- linux
install:
- git branch
- git tag
- git fetch origin master
- git branch master FETCH_HEAD
- git branch
- git tag
script: docker/kopia-alpine/build.sh kanisterio/kopia
git:
  depth: false
env:
- GO111MODULE=on
import: docker/travis.yml
