name: Build ARMHF

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build ARMHF
    runs-on: [self-hosted, armhf]
    steps:

    - name: Check out code
      uses: actions/checkout@v2

    - name: Build
      run: make